source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"


target :TRHouse do

pod 'MJExtension'
pod 'NJKWebViewProgress'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'DACircularProgress'
pod 'SVProgressHUD'
pod 'Qiniu'
pod 'HUPhotoBrowser'

end
